project_id = "hacjuanzbsvfnhffjbgo"

[api]
enabled = true
port = 54321
schemas = ['public', 'graphql_public']
extra_search_path = ['public', 'extensions']
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://da530901-96b7-4c68-837f-466dad723760.lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.resend_key_id]
verify_jwt = false