// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hacjuanzbsvfnhffjbgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhY2p1YW56YnN2Zm5oZmZqYmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjM2MTMsImV4cCI6MjA3Mzc5OTYxM30.O-D3dNHTQfYudOKgYb6aUBeZnHX7e9GuZpF0o34AxlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});