// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khjkkdllersvkkwlylhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoamtrZGxsZXJzdmtrd2x5bGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3OTU5NDgsImV4cCI6MjA4NTM3MTk0OH0.Xm7CUlG2nMINwvy08NFgAjSgPrNwQW3ynNU6ndiNSNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
